name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build
    - name: Up Docker
      run: docker-compose up -d
    - name: Bash
      run: |
        docker-compose exec -T app bash
        ls
    - name: check files
      run: |
        cd app
        npm install
      
        
